### ISSUE TITLE
Suport offline (kernel-disconnected) HTML

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Server/nbpresent#2]
Use nbconvert to generate a standalone HTML document with enough dependencies:
- [x] load from CDN
- [x] load from cannonical location (nbextensions)
- [ ] customizable prefix
- [ ] inline bundle

Caveats:
- no widgets (thebe? tmpnb? binder?)

This will require:
- jinja2 template
  - add metadata for each cell inside cell node?
  - or just `data-nbpresent-id` attribute (current approach)
- Exporter
  - inlining (plugins?)

Present experiments pointing to problems with requirejs build: `mismatched anonymous define`.

**Comment by damianavila** [comment]
I saw some PR already merged... what are the remaining steps? because I read "fair amount of work remains." in the PR :wink:
