### ISSUE TITLE
Tour too fast. 

### ISSUE THREAD

**Issue by Carreau** [Anaconda-Server/nbpresent#20]
The automatic play is too fast. 

Also clicking on next/prev should leave on "Pause" if the user have pressed Pause.

**Comment by bollwyvl** [comment]
Thanks for the feedback!

I really just created it as a way to organize my thoughts, but it has ended
up being pretty useful (screencast, etc.).

I'll have to see about the unpause behavior... i think i'm using it pretty
much as is now.

**Comment by bollwyvl** [comment]
I've changed the delay to 5s... hoping to work on some new features that will require some touring, so will take a look at the prev/pause behavior, then!

**Comment by damianavila** [comment]
ping @bollwyvl, I think this was solved some time ago... closing now, reopen if you feel different :wink:
