### ISSUE TITLE
Support key navigation and exit

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/nbpresent#26]
When "viewing" an nbpresent notebook it would be nice if arrow keys could advance slides and ESC could return to notebook editor mode.

**Comment by bollwyvl** [comment]
Sounds good. I'll probably copy what RISE does.

**Comment by bollwyvl** [comment]
This, and a raft of other things with the keyboard are in #41.

**Comment by bollwyvl** [comment]
Release as part of v1.0.0!
