### ISSUE TITLE
Create Binder

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Server/nbpresent#27]
Binder is the best way to expose potential users to the full capability of nbpresent.

- [ ] Remove existing Dockerfile
- [ ] Create new Dockerfile FROM binder-base
- [ ] Create index.ipynb
- [ ] Put in some whizzy stuff

**Comment by bollwyvl** [comment]
This is going to be the `index.ipynb` used as the home page, so we'll want a "try it in binder" ribbon or something.

**Comment by bollwyvl** [comment]
Adding a binder to this repo is less useful and potentially distracting to a new developer: having a real docker (and/or docker-compose) file for live development will be much better.

A more sane approach will be to have a binder example in another repo, and just make use of the excellent `environment.yml` feature, as done on this [experiment](https://github.com/bollwyvl/dangerous-playgrounds):
[![Binder](http://mybinder.org/badge.svg)](http://mybinder.org/repo/bollwyvl/dangerous-playgrounds)

Probably the right thing to do is to build up a `nbpresent-examples` repo a la [bokeh-notebooks](https://github.com/bokeh/bokeh-notebooks), which is intended to be used on binder. This would also make a more sane place to have all of the third-party integrations tested. Issue opened here #40.

**Comment by damianavila** [comment]
Nice!!
