### ISSUE TITLE
builds are really big

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Server/nbpresent#32]
I think some `node_modules` are slipping in. Probably don't need to ship the reference screenshots either... unless they are needed in the docs.

The next release needs to strip these out.

- [ ] fix `MANIFEST.in`

**Comment by damianavila** [comment]
IIRC, I also saw that in you setup.py you are including data_files, and IIRC that put all the `.git` repo under the package... check if that if still happening...

**Comment by bollwyvl** [comment]
I thought this would handle that:
https://github.com/Anaconda-Server/nbpresent/blob/master/MANIFEST.in#L17

**Comment by damianavila** [comment]
I did not check recently... this is just something I saw, let say, around 3 weeks ago... I will check later again...

**Comment by bollwyvl** [comment]
This has been fixed... there are perhaps still some issues when building locally, but the binstar build is clean.
