### ISSUE TITLE
Default content size

### ISSUE THREAD

**Issue by akhmerov** [Anaconda-Server/nbpresent#37]
My largest, and perhaps the only stumbling stone with nbpresent so far is the scales of everything. Since the presentation css is the same (?) as in the notebook, most things are tiny in a slideshow.

It would be great if sizes were somehow possible to adjust. (Or am I missing something obvious, and the option is already there?)

**Comment by bollwyvl** [comment]
#34 is all about that, so I'll close this one, but I do appreciate the feedback. If you have more thoughts on what you want to be able to do, please chime in there!

Today, the nickel fix to embiggen content is to use browser zoom :trollface: Actually, it works quite well, but it is pretty heavy handed.

If you are okay with hacking CSS, you can just make a cell with some raw style in it!
```
%html
<style>
  .nbpresent_present h1 {font-size: 200%}
 /* etc */
</style>
```

I don't like that much, though, and that approach isn't scalable, or reusable, long-term.

Near term (next couple weeks), the themes will just be at the deck level (one theme per slideshow) and provide a very limited number of options, configured through the GUI:
- title (h1,2,3...), body
  - font size
  - font color
  - font effect (i.e. bold)
- background
  - color
  - image
    - position
    - content (tricky: probably have to embed the whole image in metadata)

inevitably, this will create problems with the white-centric elements in the notebook, so the first challenge will be making key components (widgets, bokeh, etc.) more aware of theming.

Moving forward, we'll make it much more overrideable at the slide and region level, so you can make a giant jumbotron of a single word with an unique accent font on a slide, if you want. All of this needs to be at a _data_ level, so there will be no hacking of CSS/javascript... though of course, in the notebook, nobody can stop you from doing that!

Beyond that, there will be much richer interplay between typography and layout: my holy grail is a visually defined constraint-based layout with its base units informed by the typography: e.g. as you may have seen on some style guides, regions must be one `N` of the title font apart from other regions, and the region text must line up on a grid.

Even out beyond that is really digging into the readability/cohesiveness of a presentation, invoking best practices from typography, as well as color theory: throw an image in, get a "good" color scheme out.

All of these things present lots of challenges, as key to all of this working is _not_ breaking the regular notebook editing experience, but making it very easy to switch back and forth between the "themed" and "unthemed" approach. one should not feel 

Thanks for the continued interest!
