### ISSUE TITLE
Move examples to separate repo, binderize

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Server/nbpresent#40]
Each extra notebook with embedded stuff carries cost in package size, etc.

Further, since the development steps to go from repo to usable package are rather involved, there's no reason to make mybinder.org do that in their docker infrastructure if we're already automatically building packages.

Let's create an `nbpresent-examples` repo like [bokeh-notebooks](https://github.com/bokeh/bokeh-notebooks), with a binder (#27) using an environment.yml pointing at the built nbpresent to bring in third party libraries will lighten the base development environment considerably.

**Comment by damianavila** [comment]
:+1:

**Comment by bollwyvl** [comment]
Apparently, not going to do this.
