### ISSUE TITLE
Issue with viewing slides.. even on restart...

### ISSUE THREAD

**Issue by scollis** [Anaconda-Server/nbpresent#58]
Added Notebook.. when I click "slides" or New slides I can not see my slides in the lower part of the screen.
<img width="661" alt="screenshot 2016-02-20 12 38 14" src="https://cloud.githubusercontent.com/assets/825351/13198486/3ac109f8-d7cf-11e5-9e33-e37ed6a91129.png">
<img width="1271" alt="screenshot 2016-02-20 12 36 56" src="https://cloud.githubusercontent.com/assets/825351/13198485/3abd3b48-d7cf-11e5-8f97-9357e207d4b8.png">

**Comment by scollis** [comment]
IPyNB: https://github.com/scollis/notebooks/blob/master/NBpresent.ipynb

**Comment by scollis** [comment]
Issue on both Chrome and Firefox

**Comment by bollwyvl** [comment]
This has been fixed, tested and shipped (on conda) as 1.1.1 for all the 64-bit platforms and pythons.
```shell
conda install -c anaconda-nb-extensions nbpresent
```
Thanks @scollis for report and the notebook!
